version: '3.1'

services:
  database:
    image: mysql:8.0
    container_name: mysql-container-member
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
    ports:
      - 3317:3306
    volumes:
      - mysql-db:/var/lib/mysql

  backend:
    image: popplar-member:latest
    container_name: member
    hostname: member
    env_file:
      - .env
    ports:
      - "8201:8201"
    build:
      dockerfile: Dockerfile

volumes:
  mysql-db: