version: '3.1'

services:
  backend:
    image: api-gateway:latest
    container_name: api-gateway
    hostname: api-gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    build:
      dockerfile: Dockerfile