server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      routes:
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat/**
          filters:
            - CustomAuthFilter
        - id: hot-place-service
          uri: lb://HOT-PLACE-SERVICE
          predicates:
            - Path=/hot-place/**
          filters:
            - CustomAuthFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: GET, POST
            allowedHeaders: "*"
            maxAge: 3600
