server:
  port: 10000

spring:
  application:
    name: chat-service

eureka:
  instance:
    instance-id: chat-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
